name: Deploy Apollo Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Backend
        run: npm install

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_NAME }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/apollo/backend
            git pull
            npm install
            npm run db:gen
            pm2 restart apollo-backend
